from __future__ import annotations

import asyncio
import math
from typing import Any

import tinker

from detectors_bench.registry import DetectorConfig
from detectors_bench.schemas import Example, Prediction

from .base import DetectorWrapper

_SYSTEM_PROMPT = (
    "You are a forensic text analyst. "
    "Determine whether the text was written by a human or generated by AI."
)

_USER_TEMPLATE_PREFIX = """\
Analyze the following text and decide if it was written by a human or generated by AI.

Text:
<<<
"""

_USER_TEMPLATE_SUFFIX = """\
>>>

Output your verdict as exactly one word: AI or human."""

_ANALYSIS_STUB = "I'll analyze this text for AI vs human patterns."

# Closes the analysis channel, opens the final response channel, then primes
# the verdict token position.  Tokenizes as [..., ':', ' AI'/' human'].
_CHANNEL_CLOSE_AND_VERDICT_PREFIX = (
    "<|end|><|start|>assistant<|channel|>final<|message|>verdict:"
)

# Token IDs for ' AI' and ' human' in openai/gpt-oss-120b (single tokens each).
_TOKEN_AI = 20837     # ' AI'
_TOKEN_HUMAN = 5396   # ' human'


def _softmax2(log_a: float, log_b: float) -> tuple[float, float]:
    """Numerically stable softmax over two log-probabilities."""
    m = max(log_a, log_b)
    ea = math.exp(log_a - m)
    eb = math.exp(log_b - m)
    s = ea + eb
    return ea / s, eb / s


class GptOssDirectWrapper(DetectorWrapper):
    """Zero-shot direct classifier using gpt-oss-120b.

    Builds a prefix that ends with "verdict:" after a stub analysis channel,
    then scores P(' AI') and P(' human') via compute_logprobs_async and
    returns their softmax ratio as score_ai.
    """

    def __init__(self, cfg: DetectorConfig) -> None:
        super().__init__(cfg)
        self._base_model: str = cfg.get("base_model", "openai/gpt-oss-120b")
        self._reasoning_effort: str = cfg.get("reasoning_effort", "low")
        self._sampling_client: Any = None
        self._tokenizer: Any = None

    def _get_tokenizer(self):
        if self._tokenizer is None:
            from transformers import AutoTokenizer
            self._tokenizer = AutoTokenizer.from_pretrained(self._base_model)
        return self._tokenizer

    def _build_prefix_tokens(self, text: str) -> list[int]:
        """Return token IDs for the full prefix up to and including 'verdict:'."""
        tokenizer = self._get_tokenizer()
        user_content = _USER_TEMPLATE_PREFIX + text + _USER_TEMPLATE_SUFFIX
        # apply_chat_template with add_generation_prompt=True appends
        # <|channel|>analysis<|message|> as the generation suffix.
        prompt_str: str = tokenizer.apply_chat_template(
            [{"role": "user", "content": user_content}],
            tokenize=False,
            add_generation_prompt=True,
            reasoning_effort=self._reasoning_effort,
            model_identity=_SYSTEM_PROMPT,
        )
        full_str = prompt_str + _ANALYSIS_STUB + _CHANNEL_CLOSE_AND_VERDICT_PREFIX
        return tokenizer.encode(full_str, add_special_tokens=False)

    async def _get_sampling_client_async(self):
        if self._sampling_client is None:
            service = tinker.ServiceClient()
            self._sampling_client = await service.create_sampling_client_async(
                base_model=self._base_model
            )
        return self._sampling_client

    async def _score_one_async(
        self,
        client: Any,
        sem: asyncio.Semaphore,
        ex: Example,
    ) -> tuple[str, float | None, str]:
        async with sem:
            prefix = self._build_prefix_tokens(ex.text)
            input_ai = tinker.ModelInput.from_ints(prefix + [_TOKEN_AI])
            input_human = tinker.ModelInput.from_ints(prefix + [_TOKEN_HUMAN])
            lps_ai, lps_human = await asyncio.gather(
                client.compute_logprobs_async(input_ai),
                client.compute_logprobs_async(input_human),
            )
        log_ai = lps_ai[-1]
        log_human = lps_human[-1]
        if log_ai is None or log_human is None:
            return ex.id, None, f"log_ai={log_ai} log_human={log_human}"
        p_ai, _ = _softmax2(log_ai, log_human)
        return ex.id, p_ai, f"log_ai={log_ai:.4f} log_human={log_human:.4f} p_ai={p_ai:.4f}"

    async def _predict_batch_async(
        self,
        examples: list[Example],
        concurrency: int,
    ) -> list[tuple[str, float | None, str]]:
        client = await self._get_sampling_client_async()
        sem = asyncio.Semaphore(concurrency)
        return await asyncio.gather(
            *[self._score_one_async(client, sem, ex) for ex in examples]
        )

    def predict_one(self, ex: Example) -> Prediction:
        results = self.predict_batch([ex])
        return results[0]

    def predict_batch(self, examples: list[Example]) -> list[Prediction]:
        import time
        concurrency = int(self.cfg.get("concurrency", 64))
        try:
            results = asyncio.run(self._predict_batch_async(examples, concurrency))
        except RuntimeError:
            loop = asyncio.get_event_loop()
            results = loop.run_until_complete(self._predict_batch_async(examples, concurrency))

        id_to_result = {eid: (score, raw) for eid, score, raw in results}
        out = []
        for ex in examples:
            score, raw_text = id_to_result[ex.id]
            from detectors_bench.schemas import attach_example_metadata
            pred = Prediction(
                id=ex.id,
                detector=self.name,
                score_ai=score,
                raw_score=score,
                raw_label="AI" if (score is not None and score >= 0.5) else "human",
                pred_builtin=int(score >= 0.5) if score is not None else None,
                features={"raw": raw_text},
            )
            out.append(attach_example_metadata(pred, ex))
        return out
